name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:
 

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      run: python ./scripts/bz.py
      shell: cmd
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win_binary
        path: bin/neutralino-win_x64.exe

 
        
  create-release:
    needs: [ build-windows]
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Clean previous binaries
      run: |
        rm -f bin/neutralino-win_x64.exe
        
    - name: Download Windows build artifacts
      uses: actions/download-artifact@v2
      with:
        name: win_binary
        path: bin
        
    - name: Create Release zip
      uses: vimtor/action-zip@v1
      with:
        files: bin/neutralino-win_x64.exe bin/WebView2Loader.dll
        dest: 'bin/neutralinojs-v${{github.event.inputs.version}}.zip'
        
    - name: Create Release Notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create ${{github.event.inputs.version}}
        
    - name: Commit and Push Changelog
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Update changelog for v${{github.event.inputs.version}}' 
        add: 'CHANGELOG.md'
        tag: v${{github.event.inputs.version}}
        
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      with: 
        branch: v${{github.event.inputs.version}}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        #GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
          tag: v${{github.event.inputs.version}}
          name: Neutralinojs v${{github.event.inputs.version}} released!
          bodyFile: ./.tmprz/release_notes.md
          artifacts: 'bin/neutralinojs-v${{github.event.inputs.version}}.zip'
          
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
        
    - name: Send Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Neutralinojs v${{github.event.inputs.version}} released ðŸš€
          Changelog: https://github.com/yapcheahshen/neutralinojs/releases/tag/v${{github.event.inputs.version}}
